name: CI / CD
on: [push, pull_request]
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependences
        run: npm install
      - name: Build front
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Run server for e2e tests
        run: npm start &
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Depoly to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{  secrets.MY_RENDER_SERVICE_ID  }}
          api-key: ${{  secrets.MY_RENDER_API_KEY  }}