name: CI
on: [push, pull_request]
jobs:
  ci: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependeces
        run: npm install
      - name: Run tests
        run: npm test